### ISSUE TITLE
This line should use an "or" instead of "and" statement

### ISSUE THREAD

**Issue by Matthalp-zz** [zszyellow/WER-in-python#1]
https://github.com/zszyellow/WER-in-python/blob/master/wer.py#L35

**Comment by zszyellow** [comment]
If you just want the right answer of rate and process shorter cache-list, please delete the lines between 57 and 161 and use "or". But if you also want the result printed in aligned way, please use "and".

**Comment by pywirrarika** [comment]
Got this error:
$python WER-in-python/wer.py smtwixes/segtest/segmentedtest.wix smtwixes/segtest/wixnlp.hyp.wix 
Traceback (most recent call last):
  File "WER-in-python/wer.py", line 167, in <module>
    wer(r, h)   
File "WER-in-python/wer.py", line 38, in wer
    if d[x][y] == d[x-1][y-1] and r[x-1] == h[y-1]: 
IndexError: index -4740 is out of bounds for axis 0 with size 4739

**Comment by zszyellow** [comment]
fixed
