### ISSUE TITLE
memory overflow when the text is long

### ISSUE THREAD

**Issue by zlct-tinet** [zszyellow/WER-in-python#11]
I am trying to calculate a wer for a long text( around 2000 words),  I run it on a linux server that's memory is 32G,  but it does't return the result. instead of throwing a memory issue. Do you have any way that can improve it ?

**Comment by zszyellow** [comment]
Could you send me a screenshot of the exact error you met?
I do think 32 GB is far enough for running this simple script.

**Comment by zlct-tinet** [comment]
![image](https://user-images.githubusercontent.com/41610412/43937722-fc8aaf10-9c91-11e8-8af0-342713c253e5.png)
Please take a look this, maybe the line number is not right, I converted your script to python3.

**Comment by zszyellow** [comment]
I have tried dealing with ~6000 words in a text file using the current code on a 16GB machine. It did not report any memory overflow error like this.  Also, 2000 is far behind python list length limit. You can check if there's other factors which can cause this error and always welcome to check with the newest version of this little tool.

**Comment by N1GGO** [comment]
I have a similar problem. My reference has 430 words and the hypothesis has 498 words.
I have already figured out the following:
In the getStepList method, x and y never reach 0 at the same time. If x = 0 then y ~ 250 and if y = 0 then x is way below 0.
Then an infinite number of "d" are appended until the memory overflows.

How can I fix this problem?
