### ISSUE TITLE
If used to test Chinese, the  marked position of  EVA was   misplaced.

### ISSUE THREAD

**Issue by xhh1314** [zszyellow/WER-in-python#12]
thanks for your script!
I used to test Chinese, the result was right, but the  marked position of  EVA was   misplaced.
<pre>
REF: 沉 吟 放 拨 插 弦 中 整 顿 衣 裳 起 敛 容 的 
HYP: 沈 营 放 拨 插 全 中 整 顿 衣 裳 起 脸 容 得 
EVA: S S       S             S   S      
WER: 27.78%
</pre>

**Comment by zszyellow** [comment]
First of all, this repo is written like a small demo script so as to share some insights. 
Hence I don't have a strong intention to deal with unicode character length in this little tool. 
If you like to contribute a version of this script which can handle Chinese character, please feel free to fork this repo and update it.

some useful resources to handle unicode character display in terminal you may like to refer:
1. https://docs.python.org/3/library/unicodedata.html
2. http://www.unicode.org/reports/tr11/
