### ISSUE TITLE
index out of bounds

### ISSUE THREAD

**Issue by MichaelGuarin0** [zszyellow/WER-in-python#5]
`Traceback (most recent call last):
  File "WER-in-python/wer.py", line 203, in <module>
    wer(r, h)
  File "WER-in-python/wer.py", line 191, in wer
    list = getStepList(r, h, d)
  File "WER-in-python/wer.py", line 49, in getStepList
    elif d[x][y] == d[x-1][y-1] and r[x-1] == h[y-1] and x >= 1 and y >= 1:
IndexError: index -1054 is out of bounds for axis 0 with size 1053
`
just tried to run this out of the box and got this

**Comment by kker43** [comment]
I have the same problem， did you fix this？

**Comment by zszyellow** [comment]
Thx, asan2006
